### PR TITLE
syn based generator + proc macro

### PR DESCRIPTION
**Pull request by vakaras**
I have started implementing a new generator based on syn. Currently, it is very basic, but the following already works:
```rust
use datapond_derive::datapond;

fn main() {
    let inp = vec![(1, 2), (2, 3)];
    let out;
    datapond! {
        input inp(x: u32, y: u32)
        output out(x: u32, y: u32)
        out(x, y) :- inp(y, x).
    };
    assert!(out.len() == 2);
    assert!(out[0] == (2, 1));
    assert!(out[1] == (3, 2));
}
```

### CODE REVIEW

**Comment by lqd** [comment]
omg

**Comment by lqd** [comment]
hey @vakaras do you feel this is still WIP, do you want to add more to this PR ? or would you rather we merge it now (and I can keep working on it, looking into fixing the new tests, etc) ?

**Comment by vakaras** [comment]
@lqd If you are OK with it, then merge it. I will work on this depending on the needs of my project. Thanks!

**Comment by lqd** [comment]
🎉 🚀 :shipit: ❤️

**Comment by lqd** [comment]
thanks so much !

**Pull request merged**
